// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDsMhVNC2Wxqm66kvA44bajLbMlclUUI1c',
    appId: '1:861241042413:web:5821f6e55f89468ae4b3e4',
    messagingSenderId: '861241042413',
    projectId: 'personal-finance-43867',
    authDomain: 'personal-finance-43867.firebaseapp.com',
    storageBucket: 'personal-finance-43867.firebasestorage.app',
    measurementId: 'G-0CFWYSB08V',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDH1B4bTV8GLzi5gEJYGLVXdo5efUzuwtA',
    appId: '1:861241042413:android:b9cea493275055d4e4b3e4',
    messagingSenderId: '861241042413',
    projectId: 'personal-finance-43867',
    storageBucket: 'personal-finance-43867.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCLkdVE3hOpKPyjherj9XfFvh6yQ_Pp_Sc',
    appId: '1:861241042413:ios:8c4ad630dd8c4ebbe4b3e4',
    messagingSenderId: '861241042413',
    projectId: 'personal-finance-43867',
    storageBucket: 'personal-finance-43867.firebasestorage.app',
    iosBundleId: 'com.example.financeManagement',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDsMhVNC2Wxqm66kvA44bajLbMlclUUI1c',
    appId: '1:861241042413:web:1fb2ece7594813c4e4b3e4',
    messagingSenderId: '861241042413',
    projectId: 'personal-finance-43867',
    authDomain: 'personal-finance-43867.firebaseapp.com',
    storageBucket: 'personal-finance-43867.firebasestorage.app',
    measurementId: 'G-J0NNWX6DHT',
  );
}
